version: '3.8'

services:
  mysql:
    image: mysql:8.0.28
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpassword
    ports:
      - "3307:3306"    # Use a different host port, e.g., 3307
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
